"""corrected color temp column

Revision ID: 17e0d14586ca
Revises: c98ed2027bd3
Create Date: 2024-11-10 11:03:16.529445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e0d14586ca'
down_revision = 'c98ed2027bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_temp_k', sa.Integer(), nullable=True))
        batch_op.drop_column('color_temp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_temp', sa.INTEGER(), nullable=True))
        batch_op.drop_column('color_temp_k')

    # ### end Alembic commands ###
