"""created image table

Revision ID: c98ed2027bd3
Revises: faff4c77d87d
Create Date: 2024-11-10 10:26:11.003808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98ed2027bd3'
down_revision = 'faff4c77d87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('heading_deg', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('camera_tilt_deg', sa.Integer(), nullable=True),
    sa.Column('focal_length_mm', sa.Integer(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('shutter_speed', sa.String(), nullable=True),
    sa.Column('aperture', sa.String(), nullable=True),
    sa.Column('color_temp', sa.Integer(), nullable=True),
    sa.Column('image_format', sa.String(), nullable=True),
    sa.Column('file_size_mb', sa.Integer(), nullable=True),
    sa.Column('drone_speed_mps', sa.Integer(), nullable=True),
    sa.Column('battery_level_pct', sa.Integer(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Integer(), nullable=True),
    sa.Column('gimbal_mode', sa.String(), nullable=True),
    sa.Column('subject_detection', sa.String(), nullable=True),
    sa.Column('image_tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
